In [2]:
import torch

x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(x.shape)
print(x.dtype)
print(x + 1)
print(x @ x)

print(x.mean())
print(x.sum(dim=0))

torch.Size([2, 2])
torch.float32
tensor([[2., 3.],
        [4., 5.]])
tensor([[ 7., 10.],
        [15., 22.]])
tensor(2.5000)
tensor([4., 6.])


In [4]:
w = torch.tensor(3.0, requires_grad=True)

y = w ** 2

y.backward()

print(y)
print("Градиент (производная):", w.grad)

tensor(9., grad_fn=<PowBackward0>)
Градиент (производная): tensor(6.)
